### ISSUE TITLE
large parallelism results in database failure

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/estimagic#108]
### Bug description

All continues to work well with the previous version of `estimagic`. However, when using the most recent version with the logging capabilities, the parallel workflow breaks down. See the attached screenshots.

### To Reproduce

Unfortunately, I cannot reproduce the error on my local machine even when using `mpiexec`. We should probably discuss it over the phone on Thursday. I think I have isolated the problem to the `UserWarning` for the inability to write to the database.

### Screenshots/Error messages

![directory](https://user-images.githubusercontent.com/3607591/70565665-da4ee480-1b92-11ea-8d8a-a92cf4be77bb.png)

![logging](https://user-images.githubusercontent.com/3607591/70565663-d8852100-1b92-11ea-90ab-7abcf8e1f2a0.png)

**Comment by janosg** [comment]
Are you using the same database for several optimizations?

**Comment by tobiasraabe** [comment]
It seems like. Everything is save in ``logging.db``. Are you controlling the parallelized optimizations with estimagic or start many optimizations on your own? Because the first should rexognize that their is just one logging path and multiple optimizations Then, the path is duplicated to ``logging_1.db``, .... .

**Comment by peisenha** [comment]
I am starting multiple independent optimizations, that I each want to write to their own database. Here is the codes https://github.com/structUncertainty/analysis/tree/master/sampling-distribution, (@tobiasraabe, I send you an invite). Let me know if this helps, otherwise, let's talk on Skype and I can walk you through the code.

**Comment by tobiasraabe** [comment]
Here is the error: https://github.com/structUncertainty/analysis/blob/fa2a6820e473b593c1822949355f4bcb305b8454/sampling-distribution/core_functions.py#L53. You are calling the maximize function without a ``logging`` argument which is by default ``logging.db``. Because you start independent runs, they all log to the same database and it might crash.

To solve your issue, you should add ``logging`` to the options: https://github.com/structUncertainty/analysis/blob/fa2a6820e473b593c1822949355f4bcb305b8454/sampling-distribution/create_results.py#L57.

Or you let estimagic take care of the parallelization, but this does probably not work with the thread limits. At some point we need to work on this again.

**Comment by tobiasraabe** [comment]
Or maybe not. I missed ``dirname`` and stepping into it.

**Comment by peisenha** [comment]
Simply having unique names for all open databases solves the issue.
