### ISSUE TITLE
Make optimize.py more readable

### ISSUE THREAD

**Issue by roecla** [OpenSourceEconomics/estimagic#118]
## Current situation

`optimize.py` has become increasingly complex and hard to read over time as features have been sequentially added.

There are three main reasons for this:
1. 3 nested levels of `minimize` (`_single`, `_internal`)
2. Differing layers of abstraction
3. Scattering of tasks across the nested levels

## Desired Situation

As one of the core modules of estimagic `optimize.py` should be an easy entry point into the code. For this the `minimize` function should read like a table of contents.

### Rationale

`minimize` consists of five main steps:
1. **broadcast the user supplied arguments**
2. **clean the arguments**: 
	Generate the inputs a perfect user would supply. This step includes:
	- `_process_params`
	- `expand_criterion_output` 
	- handling maximizations
	- `process_constraints`
	- processing the algorithm (l. 477-490)
3. **create the internal inputs**: 
	This includes:
	- setting up the database
	- creating the internal objects (params, criterion, gradient)
4. **run the optimization** (l. 494-532)
5. **post processing of the optimization results**: This will include reparametrizing and harmonizing the output across supported algorithms.

The functions of 1., 2. and 5. should be imported from different modules as they are not at the core of `optimize`. The steps of 3. and 4. are central and would be included.

### Pseudo Code

```python


def minimize(...):
	# Step 1: called process_optimization_arguments at the moment
	raw_arguments, n_cores = broadcast_arguments(...) 

	# Step 2: convert to input of a perfect user
	cleaned_arguments = []
	for i, raw_arg in enumerate(raw_arguments):
		cleaned_arguments[i] = clean_and_check_arguments(raw_arg)

	# Step 3: create internal inputs
	internal_arguments = []
	for i, clean_arg in enumerate(cleaned_arguments):
		general_options, comparison_plot_data = _initial_evaluation(...)
		database = _initialize_database(...)
		
		internal_params = reparametrize_to_internal(...)
		internal_criterion = _create_internal_criterion(...)
		internal_gradient = _create_internal_gradient(...)

	# Step 4. Run the Optimization
	results = Parallel(n_jobs=n_cores)(
	    delayed(_single_minimize)(arg) for arg in internal_arguments)

	# Step 5. Process the optimization results
    results = process_optimization_results(results)
    return results
```

### Notes

- this will be much easier after the dashboard is rewritten and outside minimize
- does `process_constraints` and processing the algorithm belong to the cleaning step or to creating internal inputs?

**Comment by janosg** [comment]
Thanks a lot. That is a great proposal. Regarding the question: `process_constraints` could be in either step. But I would probably put it into creating internal inputs. 

I would rename the `create_internal_inputs` step to `rewrite_optimization_problem` or `transform_optimization_problem`.

I had always thought that in the hierarchy of optimize functions we change optimizers in the sense that we take a simple optimizer and teach it to do logging and deal with constraints. But that's not what we actually do. Instead we rewrite a complicated optimization problem such that it can be solved with a simple optimizer. Your proposal makes that explicit! This might look like a minor detail, but it is actually very important because it shows how easy it is to add new optimizers.
