### ISSUE TITLE
Dashboard loses data when refreshed.

### ISSUE THREAD

**Issue by tobiasraabe** [OpenSourceEconomics/estimagic#41]
If one refreshes the dashboard tab, all data is lost.

**Comment by janosg** [comment]
@roecla Do you have any explanation for this or a hint how I can fix it?

**Comment by tobiasraabe** [comment]
When I looked at this the last time, I had the impression that the dashboard keeps the first and incoming fitness values and parameter values.

Maybe it has something to do with the following lines, because your callback receives the initial data (params and fitness) as a partialed argument and maybe it is never updated during optimization.

https://github.com/OpenSourceEconomics/estimagic/blob/a112d205e2c96e33599adb37b11f26a079308ab3/estimagic/dashboard/dashboard.py#L64-L80

I have never fully explored this idea, but maybe it helps.

**Comment by roecla** [comment]
PR #132 improves this situation substantially because the data are permanently stored in the database. 
However, at the moment when the browser tab is refreshed, the past iterations are skipped:

Before the refresh:
![image](https://user-images.githubusercontent.com/9567321/75565401-2ac93600-5a4e-11ea-9025-be7858ecc40b.png)

After the refresh:
![image](https://user-images.githubusercontent.com/9567321/75563633-f607af80-5a4a-11ea-94e4-e86c980f8a6a.png)

I don't understand the bokeh behavior when the tab is refreshed yet. Periodic callbacks seem to continue running but cannot be removed by the handles from before the refresh. 

I am going to address this in a future pull request. Until then, users can either content themselves with the iterations after the refresh or open up a new dashboard of the database. In that case replay mode will kick in.

**Comment by roecla** [comment]
With the switch to the dashboard monitoring the database, the loss of data is no problem anymore. 

As of PR  #169 after reloading there is no problem with the line as shown above. Instead the plots are emptied and the user is back at the "start" setup (except for the `jump` argument). 

After reloading starting the convergence tab visualization anew works about 80% of the time with no apparent patterns.  If it fails, another refresh sometimes fixes the problem and allows the user to restart the playback of the optimization.

Also, simply restarting the dashboard from the command line would be an easy fix in case the restarting from within the convergence tab does not work.
