### ISSUE TITLE
Wrong order of automatically created lower bounds for sdcorr constraints

### ISSUE THREAD

**Issue by mo2561057** [OpenSourceEconomics/estimagic#48]
https://github.com/OpenSourceEconomics/estimagic/blob/b8fb31f4ac9c6b0d19dcfb16330d835a7cd1c49c/estimagic/optimization/reparametrize.py#L169

This line reassigns the cholesky coefficients such that the standard deviations are not at their original location. (The standard deviation which is the (n,n) entry of the cholesky decomposition is now at the last position) Thereafter I am getting errors because my box bounds are not valid anymore.(The code changes the lower bound of the first dim entries to zero these entries do however not only contain sd now but also non diagonal cholesky factors which can be negative) Am I using the constraints wrong or is this a mistake ?   
To me it seems like https://github.com/OpenSourceEconomics/estimagic/blob/b8fb31f4ac9c6b0d19dcfb16330d835a7cd1c49c/estimagic/optimization/reparametrize.py#L168 induces a wrong order or at least an order that is incompatible with the original lower and upper values.

**Comment by janosg** [comment]
As discussed wit @mo2561057, this is not a bug. `covariance` or `sdcorr` constraints are incompatible with any other kind of constraints, including box constraints. Also, the positiveness of the standard deviations or variances is enforced automatically by estimagic.

The change of order is not a bug. It just made for an easier implementation and comes at a low cost, since the internal covariance parameters are not really interpretable anyways.

The bug here is, that apparently there was no good error message when using and `sdcorr` constraint together with box constraints.

**Comment by janosg** [comment]
Tasks:

- Raise error message when using `covariance` or `sdcorr` constraints together with other constraints
- Make a more visible Note in the documentation
- Add a numba like section to the error message (If you think this combination of constraints should be supported ..... )

**Comment by janosg** [comment]
Contrary to what I first thought there was actually a bug in the internally created lower bouds.

**Comment by janosg** [comment]
This is solved.
