### ISSUE TITLE
Switch sign in fitness plot when called from `maximize`

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#55]
## Current Situation

The fitness plot always displays a minimization problem

## Desired situation

The dashboard knows whether it is running a maximization or minimization and changes the plot accordingly

## Possible implementation

In `estimagic.optimize` we have `_minimize` and `minimize` am `maximize`. `_minimize` is an internal function that does most of the hard work. `minimize` is a public function and adds the dashboard. `maximize` calls `minimize`. This makes it hard to pass the information on whether a maximization or minimization is run into the dashboard. We could change it in the following way:

- `_minimize` stays as it is. It's job is to provide a unified interface to minimizers from other libraries
- There is a new internal function called `_optimize` that adds the dashboard (currently in `minimize` and the sign switch when needed (currently in `maximize`). Thus it is easy to pass the relevant information into the dashboard. 
- `maximize` and `minimize` are then constructed from `_optimize` with `functools.partial`

I can do all the interface changes, but will need @roecla's help for the actual dashboard change.

**Comment by roecla** [comment]
I think we could do this much more easily by automatically adding an entry to ``criterion_kwargs`` (e.g.`` "maximization": True``) in maximize before we call ``minimize`` in it. Then we can define the internal criterion function such that it always passes the scaled fitness to the queue instead of the "true" fitness. That way the dashboard code does not have to be touched at all. 

The option to plot a transformed fitness might be more helpful in general. For example, we might want to plot the "true" likelihood instead of the log likelihood.
