### ISSUE TITLE
Change Interface of Sum and Probability Constraints to remove over-specification

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#61]
## Current Situation

When using sum and probability constraints, currently all involved parameters are part of the external params, even though one of them can be calculated from the others. During the reparametrization step we fix one of them and in the probability case enforce the remaining constraints via transformations. In this step we also make sure that the constraint holds. If we keep this we should make sure that the constraint holds in the external params vector up to floating point accurracy. 

## Proposed Change

Only specify free parameters in external params. This means that sum constraints would not do anything, i.e. could be dropped. Probability constraints would still do the transformation

## Advantages of current implemenation

- Parameter vector is easier to parse because all required transformations are done by estimagic as opposed to the user

## Advantages of Proposed Change

- No over-specification that has to be checked
- No difficulties when calculating standard errors

## Discussion

For sum constraints the current situation is clearly better because otherwise they would just be dropped. For probability constraints it could be more intuitive to only specify the free ones. A compromise would be to add another type of constraint called `free_probability`. While this ensures that everyone finds a solution they are happy with, it could also be confusing to have two very similar but slightly different options. 

@hmgaudecker and me already discussed this in #57. Maybe it's time to hear some other opinions @peisenha, @tobiasraabe, @mo2561057

**Comment by hmgaudecker** [comment]
Thanks! Sorry I am lazy, but can you just remind me what sum constraints are in the current implementation?

**Comment by janosg** [comment]
Just fixing one parameter and replace it by the target value minus all other parameters. So you would probably always prefer to do this in user code and not via estimagic.

**Comment by hmgaudecker** [comment]
> Just fixing one parameter and replace it by the target value minus all other parameters. So you would probably always prefer to do this in user code and not via estimagic.

Oh yes :-)

In general, we are talking here about saving lines like 
```a = constant - b - c``` 
in users' code. Requiring users to write this will not make estimagic any less useful for anyone. 

Saving them this "work" via the current implementation will make the statistically trained actually work more because they have to look up how exactly the standard errors are defined, what estimagic is doing precisely, etc.. In Python speak, in the current situation there simply is no obvious way to do it if your model is overspecified.

**Comment by janosg** [comment]
From my experience of using estimagic in skillmodels and respy, the benefit is not that it saves you to do the transformation. One of the most helpful constraints turned out to be fixed parameters that don't have any transformation at all! The real benefit is that you collect all kinds of parameters in one DataFrame and that it helps you to modularize your code because you can define the constraints anywhere you want in any order and just know that they are taken care of.

Having said that, I've never had any use for sum constraints ;-). I just implemented them because the cost of doing it was so low. 

For probability constraints the picture is different. Here the internal values are not just one fewer, but also transformed and there are positivity constraints. This takes more lines and will save users a lot of mental energy. But we could decide that a user only specifies the free probabilities and therefore only gets standard errors for those, even though I don't completely understand why you find it so confusing to have standard errors or confidence intervals for all probabilities. I think they can just be used and interpreted like any other standard error or confidence interval.

**Comment by hmgaudecker** [comment]
> From my experience of using estimagic in skillmodels and respy, the benefit is not that it saves you to do the transformation. One of the most helpful constraints turned out to be fixed parameters that don't have any transformation at all! The real benefit is that you collect all kinds of parameters in one DataFrame and that it helps you to modularize your code because you can define the constraints anywhere you want in any order and just know that they are taken care of.

Fair enough, but I do not see any impact whatsoever on that.

> Having said that, I've never had any use for sum constraints ;-). I just implemented them because the cost of doing it was so low.

> For probability constraints the picture is different. Here the internal values are not just one fewer, but also transformed and there are positivity constraints. This takes more lines and will save users a lot of mental energy. But we could decide that a user only specifies the free probabilities and therefore only gets standard errors for those

Oh, of course, I was not trying to suggest that removing probability constraints altogether would be a good idea. This was just about replacing them in the way we have been discussing.

> even though I don't completely understand why you find it so confusing to have standard errors or confidence intervals for all probabilities. I think they can just be used and interpreted like any other standard error or confidence interval.

If I know how you calculated them, yes. But I need to know that. By contrast, if I leave out the base category, it is clear what adjusts when I vary a coefficient, no need to describe anything. It is immediately obvious.

For the current setup, there is a multitude of valid ways of coming up with results. If I have ten categories, I could adjust the remaining 9 downwards or just one (which would that be?), two, three. Etc. etc.. I am not saying it could not be done, but it is definitely non-standard and not fully clear of what you **would** want to do. That is all stuff that you have to code up, document, explain, ... And lazy people like me will be confused and bother you with questions because they did not find the correct spot in the docs at first sight :-)

**Comment by hmgaudecker** [comment]
Okay, so I think I see a bit clearer now what you want, what my concern is, and how to find a solution

- Maybe you can find standard errors for all categories of sum / probability constraints, but other statistics will be misleading or wrong. E.g., for the J-Statistic of GMM you only want it to be based on K parameters, not on K+?. I feel very strongly that the VCOV-matrix of the estimators should be calculated and reported only for "true" parameters, i.e., those that appear in the estimation problem. This is very obvious for fixed parameters already, our discussion shows that it is less obvious for those that are implicitly fixed. If you really want, provide a bonus option to calculate the standard errors for the left-out category, but I doubt it will see much use.
- You are worried about having all relevant parameters in `params_df`. I do see the benefits of that. It can be clumsy to get back the left-out category into the form that you want.
- Once it is obvious that `len(vcov) < len(params_df)` is the norm rather than the exception (because unlike `x` in pure optimisation packages `params_df` should play a more comprehensive role -- the former is where my thoughts got their anchor from), I think the way to go is to make sure that one of the parameters is set as the base category. This could either be left to the user for flexibilty (might lead to a somewhat clumsy interface) or the first/last among the list of parameters in the sum/probability constraint.

**Comment by janosg** [comment]
Done.
